### ISSUE TITLE
Getting spawn exifToll error

### ISSUE THREAD

**Issue by NitinStar** [kapouer/url-inspector#16]
Hi, 
I am getting below error after installing url-inspector and start node. my node version is 6.10.2 and OS is Windows 10.
Error: spawn exiftool ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

**Comment by kapouer** [comment]
You need to install exiftool and make sure its executable can be found as "exiftool".
See link there https://github.com/kapouer/url-inspector#installation

**Comment by NitinStar** [comment]
Thank you. below link help me for installation.
http://owl.phy.queensu.ca/~phil/exiftool/install.html#Windows
