### ISSUE TITLE
shout when exiftool is not found

### ISSUE THREAD

**Issue by kapouer** [kapouer/url-inspector#17]
This could be a warning upon require (not really useful to shout at install time).

**Comment by albe-rosado** [comment]
Node: 8.9.1, MacOS, just trying the example in the readme, get this error:

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn exiftool ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by kapouer** [comment]
Come to think about it, there are now exiftool-vendored.pl and exiftool-vendored.exe available on npm.
Even better, the dependency on `streat` could be replaced by exiftool-vendored.js if it handled piping a readable stream to exiftool as streat do.
See also https://github.com/mceachen/exiftool-vendored.js/issues/2
